### ISSUE TITLE
main branch CI red: WorldScreen tests crash with AttributeError on npcManager/npcEnabled after #516

### ISSUE THREAD

**Issue by dmccoystephenson** [Preponderous-Software/roam#541]
## Summary
The `Tests` and `Windows Installer` CI workflows have been failing on `main` since PR #516 ("NPC/CPC autonomous agents with multi-room simulation") merged. Confirmed on main's own post-merge run (https://github.com/Preponderous-Software/roam/actions/runs/30422993111) and reproduced on an unrelated PR branch (#540) that only touches `roam.iss`/`README.md`.

```
FAILED tests/screen/test_worldScreen_initialize.py::test_initialize_saves_brand_new_world - AttributeError: Mock object has no attribute 'npcEnabled'
FAILED tests/screen/test_worldScreen_livingEntityCornerMigration.py::test_updateLivingEntities_migrates_entity_from_corner - AttributeError: 'WorldScreen' object has no attribute 'npcManager'
2 failed, 1132 passed
```

## Root cause
`WorldScreen.__init__` now unconditionally sets `self.npcManager = NpcManager(config)` (src/screen/worldScreen.py:142), and several methods (e.g. `_updateLivingEntities` at line 2521-2522) read `self.npcManager` whenever `self.config.npcEnabled` is true. `Config.npcEnabled` defaults to `True` (src/config/config.py:317).

Both failing tests construct a `WorldScreen` via `WorldScreen.__new__(WorldScreen)` (bypassing `__init__`) and hand-set only a few attributes (`config`, `graphik`, `status`, etc.) — a pattern several existing tests in `tests/screen/` use to avoid pygame/DI setup. Since `npcManager` is never set on these partial instances and `config.npcEnabled` defaults `True`, any exercised code path that touches NPC ticking now raises `AttributeError` instead of exercising the intended logic.

- `tests/screen/test_worldScreen_livingEntityCornerMigration.py::createWorldScreen` never sets `ws.npcManager`.
- `tests/screen/test_worldScreen_initialize.py::test_initialize_saves_brand_new_world` mocks `config` with a `Mock()` that has no `npcEnabled` attribute at all, so `self.config.npcEnabled` itself raises `AttributeError` before even reaching `npcManager`.

## Suggested fix
Either:
- Set `ws.npcManager = MagicMock()` (or a real `NpcManager`) in the affected tests' partial-construction helpers, matching how other `WorldScreen.__new__` tests stub out required attributes, **or**
- Have `Config`'s test double / the shared test fixture in `tests/screen/` provide a default `npcEnabled=False` (or a full `Config()`) so hand-built mocks don't silently miss new required attributes.

Given the widespread `WorldScreen.__new__(WorldScreen)` bypass pattern in `tests/screen/`, a fixture/helper update is probably lower-risk than patching each test file individually as new `WorldScreen` fields are added.

## Impact
Breaks the `Tests` and `Windows Installer` (windows-installer sub-job) CI checks on every PR against `main` until fixed — every open/future PR shows red checks unrelated to their own diff.

---
*drafted by Claude on behalf of Daniel Stephenson*

---

_This issue body was drafted during a Gardener session ([Stephenson-Software/gardener](https://github.com/Stephenson-Software/gardener))._
